# mysql 的数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/finance?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password:
  jpa:
    show-sql: true  # 在控制台打印sql
server:
  servlet:
    context-path: /manager # 访问地址：http://localhost:8081/manager/hi
  port: 8888
logging:
  level:
    com.googlecode.jsonrpc4j: debug